[supervisord]
nodaemon=true
user=root

[program:artisan-setup]
command=php /var/www/artisan package:discover --ansi
autostart=true
autorestart=false
startsecs=0
priority=1

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
priority=10